### ISSUE TITLE
Uncaught TypeError: date.localeData is not a function

### ISSUE THREAD

**Issue by zachguo** [react-component/picker#132]
After upgrading `antd` from 4.4 to 4.5 which upgrades `rc-picker` to 1.11, this error shows up whenever I open the RangePicker panel.

It's thrown by `getShortMonths` and `getWeekFirstDay`, and even a zero configuration `<RangePicker />`(no props) throws such error.

~~I'm using `moment` included in `antd` and don't use any other date libraries. There's also no configs related to `moment` in webpack or babel.~~
I'm using `"antd-dayjs-webpack-plugin": "0.0.8"`.

**Comment by afc163** [comment]
Please upgrade antd-dayjs-webpack-plugin to latest version.
